/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Book = {
  _id: string;
  _type: "book";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  author: AuthorReference;
  startDate: string;
  finishDate?: string;
  category?: CategoryReference;
  estimated: boolean;
  url?: string;
  audiobook?: boolean;
};

export type RewriteReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "rewrite";
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  rewrite?: RewriteReference;
};

export type Rewrite = {
  _id: string;
  _type: "rewrite";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug: Slug;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
};

export type Alias = {
  _id: string;
  _type: "alias";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  source: string;
  destination: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | AuthorReference
  | CategoryReference
  | Book
  | RewriteReference
  | Category
  | Rewrite
  | Slug
  | Author
  | Alias
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/queries/aliases.ts
// Variable: ALIASES_QUERY
// Query: *[_type == "alias"] {    source,    destination  }
export type ALIASES_QUERYResult = Array<{
  source: string;
  destination: string;
}>;

// Source: ./src/sanity/queries/books.ts
// Variable: BOOKS_QUERY
// Query: *[_type == "book" && finishDate ==null || finishDate >= $yearStart && finishDate <= $yearEnd] | order(startDate desc) {    _id,    audiobook,    author -> {name},    category -> {name, slug},    estimated,    finishDate,    startDate,    title,    url  }
export type BOOKS_QUERYResult = Array<
  | {
      _id: string;
      audiobook: null;
      author: null;
      category: null;
      estimated: null;
      finishDate: null;
      startDate: null;
      title: null;
      url: null;
    }
  | {
      _id: string;
      audiobook: null;
      author: null;
      category: null;
      estimated: null;
      finishDate: null;
      startDate: null;
      title: string | null;
      url: string | null;
    }
  | {
      _id: string;
      audiobook: boolean | null;
      author: {
        name: string;
      };
      category: {
        name: string;
        slug: Slug;
      } | null;
      estimated: boolean;
      finishDate: string | null;
      startDate: string;
      title: string;
      url: string | null;
    }
>;

// Source: ./src/sanity/queries/booksByCategory.ts
// Variable: BOOKS_BY_CATEGORY_QUERY
// Query: { 'books' :*[_type == "book" && finishDate != null && category->slug.current == $category] | order(startDate desc) {    _id,    audiobook,    author -> {name},    category -> {name, slug},    estimated,    finishDate,    startDate,    title,    url  },  'category' :*[_type == "category" && slug.current == $category]  }
export type BOOKS_BY_CATEGORY_QUERYResult = {
  books: Array<{
    _id: string;
    audiobook: boolean | null;
    author: {
      name: string;
    };
    category: {
      name: string;
      slug: Slug;
    } | null;
    estimated: boolean;
    finishDate: string | null;
    startDate: string;
    title: string;
    url: string | null;
  }>;
  category: Array<{
    _id: string;
    _type: "category";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name: string;
    slug: Slug;
    rewrite?: RewriteReference;
  }>;
};

// Source: ./src/sanity/queries/booksByCategoryAndYear.ts
// Variable: BOOKS_BY_YEAR_AND_CATEGORY_QUERY
// Query: { 'books' :*[_type == "book" && finishDate >= $yearStart && finishDate <= $yearEnd && category->slug.current == $category] | order(startDate desc) {    _id,    audiobook,    author -> {name},    category -> {name, slug},    estimated,    finishDate,    startDate,    title,    url  },  'category' :*[_type == "category" && slug.current == $slug]  }
export type BOOKS_BY_YEAR_AND_CATEGORY_QUERYResult = {
  books: Array<{
    _id: string;
    audiobook: boolean | null;
    author: {
      name: string;
    };
    category: {
      name: string;
      slug: Slug;
    } | null;
    estimated: boolean;
    finishDate: string | null;
    startDate: string;
    title: string;
    url: string | null;
  }>;
  category: Array<{
    _id: string;
    _type: "category";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name: string;
    slug: Slug;
    rewrite?: RewriteReference;
  }>;
};

// Source: ./src/sanity/queries/booksByYear.ts
// Variable: BOOKS_BY_YEAR_QUERY
// Query: *[_type == "book" && finishDate >= $yearStart && finishDate <= $yearEnd] | order(startDate desc) {    _id,    audiobook,    author -> {name},    category -> {name, slug},    estimated,    finishDate,    startDate,    title,    url  }
export type BOOKS_BY_YEAR_QUERYResult = Array<{
  _id: string;
  audiobook: boolean | null;
  author: {
    name: string;
  };
  category: {
    name: string;
    slug: Slug;
  } | null;
  estimated: boolean;
  finishDate: string | null;
  startDate: string;
  title: string;
  url: string | null;
}>;

// Source: ./src/sanity/queries/booksThisYear.ts
// Variable: BOOKS_THIS_YEAR_QUERY
// Query: *[_type == "book" && (finishDate == null || finishDate >= $yearStart && finishDate <= $yearEnd)] | order(startDate desc) {    _id,    audiobook,    author -> {name},    category -> {name},    estimated,    finishDate,    startDate,    title,    url  }
export type BOOKS_THIS_YEAR_QUERYResult = Array<{
  _id: string;
  audiobook: boolean | null;
  author: {
    name: string;
  };
  category: {
    name: string;
  } | null;
  estimated: boolean;
  finishDate: string | null;
  startDate: string;
  title: string;
  url: string | null;
}>;
// Variable: BOOKS_THIS_YEAR_MULTI_QUERY
// Query: { 'books': *[_type == "book" && (finishDate == null || finishDate >= $yearStart && finishDate <= $yearEnd)] | order(startDate desc) {    _id,    audiobook,    author -> {name},    category -> {name, slug},    estimated,    finishDate,    startDate,    title,    url  },  'inprogress': count(*[_type == "book" && finishDate== null  ]),  'finished': count(*[_type == "book" && (finishDate >= $yearStart && finishDate <= $yearEnd)]) }
export type BOOKS_THIS_YEAR_MULTI_QUERYResult = {
  books: Array<{
    _id: string;
    audiobook: boolean | null;
    author: {
      name: string;
    };
    category: {
      name: string;
      slug: Slug;
    } | null;
    estimated: boolean;
    finishDate: string | null;
    startDate: string;
    title: string;
    url: string | null;
  }>;
  inprogress: number;
  finished: number;
};

// Source: ./src/sanity/queries/oldestbook.ts
// Variable: OLDEST_BOOK_QUERY
// Query: *[_type == "book"] | order(finishDate asc)[0] {    finishDate}
export type OLDEST_BOOK_QUERYResult = {
  finishDate: string | null;
} | null;

// Source: ./src/sanity/queries/rewrites.ts
// Variable: REWRITES_QUERY
// Query: *[_type != "rewrite" && references(*[_type == "rewrite"]._id)]{  _type,  slug,  rewrite-> {    slug  {    current    }  }}
export type REWRITES_QUERYResult = Array<
  | {
      _type: "alias";
      slug: null;
      rewrite: null;
    }
  | {
      _type: "author";
      slug: null;
      rewrite: null;
    }
  | {
      _type: "book";
      slug: null;
      rewrite: null;
    }
  | {
      _type: "category";
      slug: Slug;
      rewrite: {
        slug: {
          current: string;
        };
      } | null;
    }
  | {
      _type: "sanity.fileAsset";
      slug: null;
      rewrite: null;
    }
  | {
      _type: "sanity.imageAsset";
      slug: null;
      rewrite: null;
    }
>;
