/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: node_modules/@lucasamos/sanity-studio/schema.json
export type TechStack = {
  _id: string;
  _type: "techStack";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  skills: Array<string>;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Book = {
  _id: string;
  _type: "book";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  ISBN?: number;
  title: string;
  author: AuthorReference;
  startDate: string;
  finishDate?: string;
  category?: CategoryReference;
  estimated: boolean;
  url?: string;
  audiobook?: boolean;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug: Slug;
  name?: string;
};

export type Alias = {
  _id: string;
  _type: "alias";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  source: string;
  destination: string;
};

export type AboutReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "about";
};

export type Cv = {
  _id: string;
  _type: "cv";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  parentPage?: AboutReference;
  slug: Slug;
  title: string;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type TechStackSectionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "techStackSection";
};

export type About = {
  _id: string;
  _type: "about";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug: Slug;
  title: string;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  imageRow?: ImageRow;
  techStack?: TechStackSectionReference;
};

export type TechStackReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "techStack";
};

export type TechStackSection = {
  _id: string;
  _type: "techStackSection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  techStackSection: Array<
    {
      _key: string;
    } & TechStackReference
  >;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageRow = {
  _type: "imageRow";
  images: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    _type: "image";
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | TechStack
  | AuthorReference
  | CategoryReference
  | Book
  | Category
  | Slug
  | Author
  | Alias
  | AboutReference
  | Cv
  | TechStackSectionReference
  | About
  | TechStackReference
  | TechStackSection
  | SanityImageAssetReference
  | ImageRow
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries/about.tsx
// Variable: ABOUT_QUERY
// Query: *[_type == "about" && slug.current=="about"]{  title,   content,  techStack -> {  techStackSection[] -> {    title,    skills  }},  imageRow {  images[]{    ...,    asset-> {      url,      metadata {      lqip      }    }  } }}
export type ABOUT_QUERY_RESULT = Array<{
  title: string;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  techStack: {
    techStackSection: Array<{
      title: string;
      skills: Array<string>;
    }>;
  } | null;
  imageRow: {
    images: Array<{
      asset: {
        url: string;
        metadata: {
          lqip: string | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      _type: "image";
      _key: string;
    }>;
  } | null;
}>;

// Source: src/sanity/queries/aliases.ts
// Variable: ALIASES_QUERY
// Query: *[_type == "alias"] {    source,    destination  }
export type ALIASES_QUERY_RESULT = Array<{
  source: string;
  destination: string;
}>;

// Source: src/sanity/queries/books.ts
// Variable: BOOKS_QUERY
// Query: *[_type == "book" && finishDate ==null || finishDate >= $yearStart && finishDate <= $yearEnd] | order(startDate desc) {    _id,    audiobook,    author -> {name, slug},    category -> {name, slug},    estimated,    finishDate,    startDate,    title,    url  }
export type BOOKS_QUERY_RESULT = Array<
  | {
      _id: string;
      audiobook: null;
      author: null;
      category: null;
      estimated: null;
      finishDate: null;
      startDate: null;
      title: null;
      url: null;
    }
  | {
      _id: string;
      audiobook: null;
      author: null;
      category: null;
      estimated: null;
      finishDate: null;
      startDate: null;
      title: string;
      url: null;
    }
  | {
      _id: string;
      audiobook: null;
      author: null;
      category: null;
      estimated: null;
      finishDate: null;
      startDate: null;
      title: string | null;
      url: string;
    }
  | {
      _id: string;
      audiobook: boolean | null;
      author: {
        name: string | null;
        slug: Slug;
      };
      category: {
        name: string;
        slug: Slug;
      } | null;
      estimated: boolean;
      finishDate: string | null;
      startDate: string;
      title: string;
      url: string | null;
    }
>;

// Source: src/sanity/queries/booksByAuthor.ts
// Variable: BOOKS_BY_AUTHOR_QUERY
// Query: { 'books' :*[_type == "book" && finishDate != null && author->slug.current== $slug] | order(startDate desc) {    _id,    audiobook,    author -> {name, slug},    category -> {name, slug},    estimated,    finishDate,    startDate,    title,    url  },  'author' :*[_type == "author" && slug.current == $slug]  }
export type BOOKS_BY_AUTHOR_QUERY_RESULT = {
  books: Array<{
    _id: string;
    audiobook: boolean | null;
    author: {
      name: string | null;
      slug: Slug;
    };
    category: {
      name: string;
      slug: Slug;
    } | null;
    estimated: boolean;
    finishDate: string | null;
    startDate: string;
    title: string;
    url: string | null;
  }>;
  author: Array<{
    _id: string;
    _type: "author";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    slug: Slug;
    name?: string;
  }>;
};

// Source: src/sanity/queries/booksByCategory.ts
// Variable: BOOKS_BY_CATEGORY_QUERY
// Query: { 'books' :*[_type == "book" && finishDate != null && category->slug.current == $category] | order(startDate desc) {    _id,    audiobook,    author -> {name, slug},    category -> {name, slug},    estimated,    finishDate,    startDate,    title,    url  },  'category' :*[_type == "category" && slug.current == $category]  }
export type BOOKS_BY_CATEGORY_QUERY_RESULT = {
  books: Array<{
    _id: string;
    audiobook: boolean | null;
    author: {
      name: string | null;
      slug: Slug;
    };
    category: {
      name: string;
      slug: Slug;
    } | null;
    estimated: boolean;
    finishDate: string | null;
    startDate: string;
    title: string;
    url: string | null;
  }>;
  category: Array<{
    _id: string;
    _type: "category";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name: string;
    slug: Slug;
  }>;
};

// Source: src/sanity/queries/booksByCategoryAndYear.ts
// Variable: BOOKS_BY_YEAR_AND_CATEGORY_QUERY
// Query: { 'books' :*[_type == "book" && finishDate >= $yearStart && finishDate <= $yearEnd && category->slug.current == $category] | order(startDate desc) {    _id,    audiobook,    author -> {name, slug},    category -> {name, slug},    estimated,    finishDate,    startDate,    title,    url  },  'category' :*[_type == "category" && slug.current == $slug]  }
export type BOOKS_BY_YEAR_AND_CATEGORY_QUERY_RESULT = {
  books: Array<{
    _id: string;
    audiobook: boolean | null;
    author: {
      name: string | null;
      slug: Slug;
    };
    category: {
      name: string;
      slug: Slug;
    } | null;
    estimated: boolean;
    finishDate: string | null;
    startDate: string;
    title: string;
    url: string | null;
  }>;
  category: Array<{
    _id: string;
    _type: "category";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name: string;
    slug: Slug;
  }>;
};

// Source: src/sanity/queries/booksByYear.ts
// Variable: BOOKS_BY_YEAR_QUERY
// Query: *[_type == "book" && finishDate >= $yearStart && finishDate <= $yearEnd] | order(startDate desc) {    _id,    audiobook,    author -> {name, slug},    category -> {name, slug},    estimated,    finishDate,    startDate,    title,    url  }
export type BOOKS_BY_YEAR_QUERY_RESULT = Array<{
  _id: string;
  audiobook: boolean | null;
  author: {
    name: string | null;
    slug: Slug;
  };
  category: {
    name: string;
    slug: Slug;
  } | null;
  estimated: boolean;
  finishDate: string | null;
  startDate: string;
  title: string;
  url: string | null;
}>;

// Source: src/sanity/queries/booksThisYear.ts
// Variable: BOOKS_THIS_YEAR_QUERY
// Query: *[_type == "book" && (finishDate == null || finishDate >= $yearStart && finishDate <= $yearEnd)] | order(startDate desc) {    _id,    audiobook,    author -> {name},    category -> {name},    estimated,    finishDate,    startDate,    title,    url  }
export type BOOKS_THIS_YEAR_QUERY_RESULT = Array<{
  _id: string;
  audiobook: boolean | null;
  author: {
    name: string | null;
  };
  category: {
    name: string;
  } | null;
  estimated: boolean;
  finishDate: string | null;
  startDate: string;
  title: string;
  url: string | null;
}>;

// Source: src/sanity/queries/booksThisYear.ts
// Variable: BOOKS_THIS_YEAR_MULTI_QUERY
// Query: { 'books': *[_type == "book" && (finishDate == null || finishDate >= $yearStart && finishDate <= $yearEnd)] | order(startDate desc) {    _id,    audiobook,    author -> {name, slug},    category -> {name, slug},    estimated,    finishDate,    startDate,    title,    url  },  'inprogress': count(*[_type == "book" && finishDate== null  ]),  'finished': count(*[_type == "book" && (finishDate >= $yearStart && finishDate <= $yearEnd)]) }
export type BOOKS_THIS_YEAR_MULTI_QUERY_RESULT = {
  books: Array<{
    _id: string;
    audiobook: boolean | null;
    author: {
      name: string | null;
      slug: Slug;
    };
    category: {
      name: string;
      slug: Slug;
    } | null;
    estimated: boolean;
    finishDate: string | null;
    startDate: string;
    title: string;
    url: string | null;
  }>;
  inprogress: number;
  finished: number;
};

// Source: src/sanity/queries/cv.tsx
// Variable: CV_QUERY
// Query: *[_type == "cv" && slug.current=="cv"]{      parentPage -> {      title    },    title,     content  }
export type CV_QUERY_RESULT = Array<{
  parentPage: {
    title: string;
  } | null;
  title: string;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
}>;

// Source: src/sanity/queries/oldestbook.ts
// Variable: OLDEST_BOOK_QUERY
// Query: *[_type == "book"] | order(finishDate asc)[0] {    finishDate}
export type OLDEST_BOOK_QUERY_RESULT = {
  finishDate: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n*[_type == "about" && slug.current=="about"]{\n  title, \n  content,\n  techStack -> {\n  techStackSection[] -> {\n    title,\n    skills\n  }\n},\n  imageRow {\n  images[]{\n    ...,\n    asset-> {\n      url,\n      metadata {\n      lqip\n      }\n    }\n  }\n }\n}\n': ABOUT_QUERY_RESULT;
    '\n   *[_type == "alias"] {\n    source,\n    destination\n  }\n': ALIASES_QUERY_RESULT;
    '\n   *[_type == "book" && finishDate ==null || finishDate >= $yearStart && finishDate <= $yearEnd] | order(startDate desc) {\n    _id,\n    audiobook,\n    author -> {name, slug},\n    category -> {name, slug},\n    estimated,\n    finishDate,\n    startDate,\n    title,\n    url\n  }\n': BOOKS_QUERY_RESULT;
    "\n  { 'books' :*[_type == \"book\" && finishDate != null && author->slug.current== $slug] | order(startDate desc) {\n    _id,\n    audiobook,\n    author -> {name, slug},\n    category -> {name, slug},\n    estimated,\n    finishDate,\n    startDate,\n    title,\n    url\n  },\n  'author' :*[_type == \"author\" && slug.current == $slug]\n  }\n": BOOKS_BY_AUTHOR_QUERY_RESULT;
    "\n  { 'books' :*[_type == \"book\" && finishDate != null && category->slug.current == $category] | order(startDate desc) {\n    _id,\n    audiobook,\n    author -> {name, slug},\n    category -> {name, slug},\n    estimated,\n    finishDate,\n    startDate,\n    title,\n    url\n  },\n  'category' :*[_type == \"category\" && slug.current == $category]\n  }\n": BOOKS_BY_CATEGORY_QUERY_RESULT;
    "\n  { 'books' :*[_type == \"book\" && finishDate >= $yearStart && finishDate <= $yearEnd && category->slug.current == $category] | order(startDate desc) {\n    _id,\n    audiobook,\n    author -> {name, slug},\n    category -> {name, slug},\n    estimated,\n    finishDate,\n    startDate,\n    title,\n    url\n  },\n  'category' :*[_type == \"category\" && slug.current == $slug]\n  }\n": BOOKS_BY_YEAR_AND_CATEGORY_QUERY_RESULT;
    '\n  *[_type == "book" && finishDate >= $yearStart && finishDate <= $yearEnd] | order(startDate desc) {\n    _id,\n    audiobook,\n    author -> {name, slug},\n    category -> {name, slug},\n    estimated,\n    finishDate,\n    startDate,\n    title,\n    url\n  }\n': BOOKS_BY_YEAR_QUERY_RESULT;
    '\n  *[_type == "book" && (finishDate == null || finishDate >= $yearStart && finishDate <= $yearEnd)] | order(startDate desc) {\n    _id,\n    audiobook,\n    author -> {name},\n    category -> {name},\n    estimated,\n    finishDate,\n    startDate,\n    title,\n    url\n  }\n': BOOKS_THIS_YEAR_QUERY_RESULT;
    "\n  { 'books': *[_type == \"book\" && (finishDate == null || finishDate >= $yearStart && finishDate <= $yearEnd)] | order(startDate desc) {\n    _id,\n    audiobook,\n    author -> {name, slug},\n    category -> {name, slug},\n    estimated,\n    finishDate,\n    startDate,\n    title,\n    url\n  },\n  'inprogress': count(*[_type == \"book\" && finishDate== null  ]),\n  'finished': count(*[_type == \"book\" && (finishDate >= $yearStart && finishDate <= $yearEnd)]) \n}\n": BOOKS_THIS_YEAR_MULTI_QUERY_RESULT;
    '\n    *[_type == "cv" && slug.current=="cv"]{\n      parentPage -> {\n      title\n    },\n    title, \n    content\n  }\n': CV_QUERY_RESULT;
    '\n*[_type == "book"] | order(finishDate asc)[0] {\n    finishDate\n}\n': OLDEST_BOOK_QUERY_RESULT;
  }
}
